version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: prashant
       MYSQL_DATABASE: wordpress
       MYSQL_USER: prashant
       MYSQL_PASSWORD: prashant

   wordpress:
     depends_on:
       - db
     image: wordpress
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: prashant
       WORDPRESS_DB_PASSWORD: prashant
       WORDPRESS_DB_NAME: wordpress
volumes:
    data: {}

