--- #first

- hosts: all
  user: ansible
  connection: ssh
  become: yes

  tasks:
    - name: install httpd
      action: yum pkg="httpd" state="present"
      notify: 
        - start
        - deploy

  handlers:
    - name: start
      action: service name="httpd" state="started"
    - name: deploy
      action: copy src="/home/ansible/index.html" dest="/var/www/html/"
